require: rubocop-rails

AllCops:
  Exclude:
    - examples/**/*
    - lib/tasks/auto_annotate_models.rake

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/NumericLiterals:
  Enabled: false
